import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { HttpClient } from '@angular/common/http';
import { Patient } from '../components/apps-hospital-patients-create/apps-hospital-patients-create.component';

@Injectable({
  providedIn: 'root',
})
export class PatientService {
  private patients: Patient[] = [
    {
      patientID: 'P001',
      image: 'assets/images/avatar/user-1.png',
      firstName: 'John',
      middleName: 'A.',
      lastName: 'Doe',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '70 kg',
      height: '175 cm',
      bloodPressure: '120/80',
      phoneNumber: '+1 555 987 6543',
      emergencyNumber: '+1 555 123 4567',
      email: 'john.doe@example.com',
      occupation: 'Software Developer',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Sample Country',
      zipCode: '12345',
      familyDoctorName: 'Dr. Alice Smith',
      referringDoctorName: 'Dr. Bob Johnson',
      assignedDoctorName: 'Dr. Carol White',
      pharmacyName: 'Health Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'General Checkup',
      date: '15 Aug, 2023',
    },
    {
      patientID: 'P002',
      image: 'assets/images/avatar/user-2.png',
      firstName: 'John',
      middleName: 'A.',
      lastName: 'Doe',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '70 kg',
      height: '175 cm',
      bloodPressure: '120/80',
      phoneNumber: '+1 555 123 4567',
      emergencyNumber: '+1 555 987 6543',
      email: 'john@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Algeria',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Michael',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Cardiology',
      date: '05 May, 2024',
    },
    {
      patientID: 'P003',
      image: 'assets/images/avatar/user-3.png',
      firstName: 'Jane',
      middleName: 'A.',
      lastName: 'Smith',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '60 kg',
      height: '165 cm',
      bloodPressure: '120/80',
      phoneNumber: '+44 20 7946 0958',
      emergencyNumber: '+44 20 1234 5678',
      email: 'jane@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Argentina',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Sarah',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Dermatology',
      date: '12 May, 2024',
    },
    {
      patientID: 'P004',
      image: 'assets/images/avatar/user-4.png',
      firstName: 'Alice',
      middleName: 'A.',
      lastName: 'Johnson',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '55 kg',
      height: '160 cm',
      bloodPressure: '120/80',
      phoneNumber: '+61 2 9374 4000',
      emergencyNumber: '+61 2 1234 5678',
      email: 'alice@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Belgium',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Robert',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Neurology',
      date: '19 June, 2024',
    },
    {
      patientID: 'P005',
      image: 'assets/images/avatar/user-5.png',
      firstName: 'Robert',
      middleName: 'A.',
      lastName: 'Brown',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '75 kg',
      height: '180 cm',
      bloodPressure: '120/80',
      phoneNumber: '+49 30 123456',
      emergencyNumber: '+49 30 987654',
      email: 'robert@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Mexico',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Emily',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Orthopedics',
      date: '09 Feb, 2024',
    },
    {
      patientID: 'P006',
      image: 'assets/images/avatar/user-6.png',
      firstName: 'Emily',
      middleName: 'A.',
      lastName: 'Davis',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '55 kg',
      height: '165 cm',
      bloodPressure: '120/80',
      phoneNumber: '+33 1 42 68 53 00',
      emergencyNumber: '+33 1 12 34 56 78',
      email: 'emily@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Russia',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. James',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Pediatrics',
      date: '28 Jan, 2024',
    },
    {
      patientID: 'P007',
      image: 'assets/images/avatar/user-7.png',
      firstName: 'Michael',
      middleName: 'A.',
      lastName: 'Wilson',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '80 kg',
      height: '175 cm',
      bloodPressure: '120/80',
      phoneNumber: '+34 91 123 45 67',
      emergencyNumber: '+34 91 765 43 21',
      email: 'michael@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Denmark',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Olivia',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Gastroenterology',
      date: '23 June, 2024',
    },
    {
      image: 'assets/images/avatar/user-8.png',
      patientID: 'P008',
      firstName: 'Sarah',
      middleName: 'A.',
      lastName: 'Moore',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '65 kg',
      height: '170 cm',
      bloodPressure: '120/80',
      phoneNumber: '+81 3 1234 5678',
      emergencyNumber: '+81 3 9876 5432',
      email: 'sarah@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Sudan',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. David',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Oncology',
      date: '16 Dec, 2023',
    },
    {
      patientID: 'P009',
      image: 'assets/images/avatar/user-9.png',
      firstName: 'James',
      middleName: 'A.',
      lastName: 'Taylor',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '85 kg',
      height: '180 cm',
      bloodPressure: '120/80',
      phoneNumber: '+91 22 1234 5678',
      emergencyNumber: '+91 22 8765 4321',
      email: 'james@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Spain',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Sophia',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Urology',
      date: '06 Sep, 2024',
    },
    {
      patientID: 'P0010',
      image: 'assets/images/avatar/user-10.png',
      firstName: 'Laura',
      middleName: 'A.',
      lastName: 'Anderson',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '60 kg',
      height: '165 cm',
      bloodPressure: '120/80',
      phoneNumber: '+7 495 123-45-67',
      emergencyNumber: '+7 495 765-43-21',
      email: 'laura@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Germany',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. William',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'General Medicine',
      date: '21 Nov, 2023',
    },
    {
      patientID: 'P0011',
      image: 'assets/images/avatar/user-11.png',
      firstName: 'David',
      middleName: 'A.',
      lastName: 'Thomas',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '75 kg',
      height: '180 cm',
      bloodPressure: '120/80',
      phoneNumber: '+55 11 1234-5678',
      emergencyNumber: '+55 11 8765-4321',
      email: 'david@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Israel',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Charlotte',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Cardiology',
      date: '10 March, 2024',
    },
    {
      patientID: 'P0012',
      image: 'assets/images/avatar/user-12.png',
      firstName: 'Jessica',
      middleName: 'A.',
      lastName: 'Lee',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '50 kg',
      height: '160 cm',
      bloodPressure: '120/80',
      phoneNumber: '+27 11 123 4567',
      emergencyNumber: '+27 11 765 4321',
      email: 'jessica@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Denmark',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Henry',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Dermatology',
      date: '17 March, 2024',
    },
    {
      patientID: 'P0013',
      image: 'assets/images/avatar/user-13.png',
      firstName: 'Daniel',
      middleName: 'A.',
      lastName: 'Martin',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '70 kg',
      height: '175 cm',
      bloodPressure: '120/80',
      phoneNumber: '+65 6 1234 567',
      emergencyNumber: '+65 6 7654 321',
      email: 'daniel@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Russia',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Mia',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Neurology',
      date: '27 Feb, 2024',
    },
    {
      patientID: 'P0014',
      image: 'assets/images/avatar/user-14.png',
      firstName: 'Sophia',
      middleName: 'A.',
      lastName: 'Harris',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '60 kg',
      height: '165 cm',
      bloodPressure: '120/80',
      phoneNumber: '+39 06 123 4567',
      emergencyNumber: '+39 06 765 4321',
      email: 'sophia@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Mexico',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Benjamin',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Oncology',
      date: '30 March, 2024',
    },
    {
      patientID: 'P0015',
      image: 'assets/images/avatar/user-1.png',
      firstName: 'John',
      middleName: 'A.',
      lastName: 'Doe',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '70 kg',
      height: '175 cm',
      bloodPressure: '120/80',
      phoneNumber: '+1 555 987 6543',
      emergencyNumber: '+1 555 123 4567',
      email: 'john.doe@example.com',
      occupation: 'Software Developer',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Sample Country',
      zipCode: '12345',
      familyDoctorName: 'Dr. Alice Smith',
      referringDoctorName: 'Dr. Bob Johnson',
      assignedDoctorName: 'Dr. Carol White',
      pharmacyName: 'Health Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'General Checkup',
      date: '15 Aug, 2023',
    },
    {
      patientID: 'P0016',
      image: 'assets/images/avatar/user-2.png',
      firstName: 'John',
      middleName: 'A.',
      lastName: 'Doe',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '70 kg',
      height: '175 cm',
      bloodPressure: '120/80',
      phoneNumber: '+1 555 123 4567',
      emergencyNumber: '+1 555 987 6543',
      email: 'john@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Algeria',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Michael',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Cardiology',
      date: '05 May, 2024',
    },
    {
      patientID: 'P0017',
      image: 'assets/images/avatar/user-3.png',
      firstName: 'Jane',
      middleName: 'A.',
      lastName: 'Smith',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '60 kg',
      height: '165 cm',
      bloodPressure: '120/80',
      phoneNumber: '+44 20 7946 0958',
      emergencyNumber: '+44 20 1234 5678',
      email: 'jane@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Argentina',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Sarah',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Dermatology',
      date: '12 May, 2024',
    },
    {
      patientID: 'P0018',
      image: 'assets/images/avatar/user-4.png',
      firstName: 'Alice',
      middleName: 'A.',
      lastName: 'Johnson',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '55 kg',
      height: '160 cm',
      bloodPressure: '120/80',
      phoneNumber: '+61 2 9374 4000',
      emergencyNumber: '+61 2 1234 5678',
      email: 'alice@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Belgium',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Robert',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Neurology',
      date: '19 June, 2024',
    },
    {
      patientID: 'P0019',
      image: 'assets/images/avatar/user-5.png',
      firstName: 'Robert',
      middleName: 'A.',
      lastName: 'Brown',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '75 kg',
      height: '180 cm',
      bloodPressure: '120/80',
      phoneNumber: '+49 30 123456',
      emergencyNumber: '+49 30 987654',
      email: 'robert@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Mexico',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Emily',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Orthopedics',
      date: '09 Feb, 2024',
    },
    {
      patientID: 'P0020',
      image: 'assets/images/avatar/user-6.png',
      firstName: 'Emily',
      middleName: 'A.',
      lastName: 'Davis',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '55 kg',
      height: '165 cm',
      bloodPressure: '120/80',
      phoneNumber: '+33 1 42 68 53 00',
      emergencyNumber: '+33 1 12 34 56 78',
      email: 'emily@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Russia',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. James',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Pediatrics',
      date: '28 Jan, 2024',
    },
    {
      patientID: 'P0021',
      image: 'assets/images/avatar/user-7.png',
      firstName: 'Michael',
      middleName: 'A.',
      lastName: 'Wilson',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '80 kg',
      height: '175 cm',
      bloodPressure: '120/80',
      phoneNumber: '+34 91 123 45 67',
      emergencyNumber: '+34 91 765 43 21',
      email: 'michael@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Denmark',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Olivia',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Gastroenterology',
      date: '23 June, 2024',
    },
    {
      patientID: 'P0022',
      image: 'assets/images/avatar/user-8.png',
      firstName: 'Sarah',
      middleName: 'A.',
      lastName: 'Moore',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '65 kg',
      height: '170 cm',
      bloodPressure: '120/80',
      phoneNumber: '+81 3 1234 5678',
      emergencyNumber: '+81 3 9876 5432',
      email: 'sarah@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Sudan',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. David',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Oncology',
      date: '16 Dec, 2023',
    },
    {
      patientID: 'P0023',
      image: 'assets/images/avatar/user-9.png',
      firstName: 'James',
      middleName: 'A.',
      lastName: 'Taylor',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '85 kg',
      height: '180 cm',
      bloodPressure: '120/80',
      phoneNumber: '+91 22 1234 5678',
      emergencyNumber: '+91 22 8765 4321',
      email: 'james@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Spain',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Sophia',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Urology',
      date: '06 Sep, 2024',
    },
    {
      patientID: 'P0024',
      image: 'assets/images/avatar/user-10.png',
      firstName: 'Laura',
      middleName: 'A.',
      lastName: 'Anderson',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '60 kg',
      height: '165 cm',
      bloodPressure: '120/80',
      phoneNumber: '+7 495 123-45-67',
      emergencyNumber: '+7 495 765-43-21',
      email: 'laura@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Germany',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. William',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'General Medicine',
      date: '21 Nov, 2023',
    },
    {
      patientID: 'P0025',
      image: 'assets/images/avatar/user-11.png',
      firstName: 'David',
      middleName: 'A.',
      lastName: 'Thomas',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '75 kg',
      height: '180 cm',
      bloodPressure: '120/80',
      phoneNumber: '+55 11 1234-5678',
      emergencyNumber: '+55 11 8765-4321',
      email: 'david@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Israel',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Charlotte',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Cardiology',
      date: '10 March, 2024',
    },
    {
      patientID: 'P0026',
      image: 'assets/images/avatar/user-12.png',
      firstName: 'Jessica',
      middleName: 'A.',
      lastName: 'Lee',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '50 kg',
      height: '160 cm',
      bloodPressure: '120/80',
      phoneNumber: '+27 11 123 4567',
      emergencyNumber: '+27 11 765 4321',
      email: 'jessica@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Denmark',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Henry',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Dermatology',
      date: '17 March, 2024',
    },
    {
      patientID: 'P0027',
      image: 'assets/images/avatar/user-13.png',
      firstName: 'Daniel',
      middleName: 'A.',
      lastName: 'Martin',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Male',
      weight: '70 kg',
      height: '175 cm',
      bloodPressure: '120/80',
      phoneNumber: '+65 6 1234 567',
      emergencyNumber: '+65 6 7654 321',
      email: 'daniel@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Russia',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Mia',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'Yes',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Neurology',
      date: '27 Feb, 2024',
    },
    {
      patientID: 'P0028',
      image: 'assets/images/avatar/user-14.png',
      firstName: 'Sophia',
      middleName: 'A.',
      lastName: 'Harris',
      dateOfBirth: '01 Jan, 2000',
      age: 24,
      gender: 'Female',
      weight: '60 kg',
      height: '165 cm',
      bloodPressure: '120/80',
      phoneNumber: '+39 06 123 4567',
      emergencyNumber: '+39 06 765 4321',
      email: 'sophia@example.com',
      occupation: 'Sample Occupation',
      city: 'Sample City',
      state: 'Sample State',
      country: 'Mexico',
      zipCode: '12345',
      familyDoctorName: 'Dr. Sample',
      referringDoctorName: 'Dr. Sample',
      assignedDoctorName: 'Dr. Benjamin',
      pharmacyName: 'Sample Pharmacy',
      insuranceOption: 'No',
      insuranceName: 'SampleInsurance',
      insurancePolicyNumber: 'SAMPLE123456',
      startDate: '01 Jan, 2023',
      effectiveDate: '01 Jan, 2023',
      treatmentType: 'Oncology',
      date: '30 March, 2024',
    },
  ];

  constructor() {}

  getPatient(): Observable<Patient[]> {
    return of(this.patients);
  }

  addPatient(patient: Patient): Observable<Patient> {
    if (Array.isArray(this.patients)) {
      this.patients = [patient, ...this.patients];
    }
    return of(patient);
  }

  updatePatient(updatedPatient: Patient): Observable<Patient> {
    const updatedPatients = this.patients.map((patient) =>
      patient.patientID === updatedPatient.patientID ? updatedPatient : patient
    );

    this.patients = [...updatedPatients];

    return of(updatedPatient);
  }

  deletePatient(id: string): Observable<void> {
    this.patients = this.patients.filter((p) => p.patientID !== id);
    return of(void 0);
  }
}
