name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clear Yarn Cache
      run: yarn cache clean 

    - name: Install dependencies
      run: yarn install

    - name: Build Angular app
      run: yarn build

    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        source: "dist/"
        target: "/var/www/html/"